website/views.py
import os
import uuid
from flask import Blueprint, render_template, redirect, request, flash , url_for, send_from_directory
from flask_login import  login_required, current_user
from .models import Candidate, Recruiter, Offer, Application
from sqlalchemy.sql import func 
from . import db 
from .extras import is_float, sendMail, limit_string, is_offer_in_array
from PIL import Image
from datetime import datetime, date
import re 
from flask_bcrypt import generate_password_hash, check_password_hash



views = Blueprint('views', __name__ )

upload_resume = views.root_path + '/static/resume'
upload_image = views.root_path + '/static/images'

@views.route('/serve-resume/<filename>')
def serve_resume(filename):
    return send_from_directory(upload_resume, filename)

@views.route('/serve-picture/<filename>')
def serve_picture(filename):
    return send_from_directory(upload_image, filename)

@views.route('/', methods=['GET', 'POST'])
def home():

    if isinstance(current_user, Candidate):
        return redirect('/home-candidate')
    elif isinstance(current_user, Recruiter):
        return redirect('/home-recruiter')

    ofs = Offer.query.filter_by(status='active').all()
    regions = Offer.query.with_entities(Offer.region.distinct()).all()
    companies = Recruiter.query.with_entities(Recruiter.company.distinct()).all()

    if request.method == 'POST':
        position = request.form.get('position')
        category = request.form.get('category')
        company = request.form.get('company')
        region = request.form.get('region')

        if (position == '' or position is None ) and category == 'Select your Category' and company == 'Select your Company' and region == 'Select your Region':
            return render_template('index.html', offers=ofs[:8] , regions=regions, companies=companies, position=None, category=None, region=None, company=None)

        ps = []
        cats = []
        comps = []
        regs = []

        if position != '' and not None:
            positions = Offer.query.filter(Offer.position.like('%'+position+'%')).all()
            
            for pos in positions:
                if is_offer_in_array(pos, ofs):
                    ps.append(pos)

        if category != 'Select your Category':
            categories = Offer.query.filter(Offer.category.like('%'+category+'%')).all()
            
            for c in categories:
                if is_offer_in_array(c, ofs):
                    cats.append(c)
        
        if company != 'Select your Company':
            for c in ofs:
                print("\n\n\n"+str(c.recruiter)+"\t"+str(c.id)+"\n\n\n")
                if c.recruiter.company == company:
                    comps.append(c)
        
        if region != 'Select your Region':
            ions = Offer.query.filter(Offer.region.like('%'+region+'%')).all()
            
            for r in ions:
                if is_offer_in_array(r, ofs):
                    regs.append(r)

        ars = [ ps, cats, comps, regs]
        bigs = max(len(array) for array in ars)
        biggest = max(ars, key=lambda array: len(array), default=[])

        
        all_offers = []

        for i in biggest:
            valid = True 
            if position != '' and not None:
                if is_offer_in_array(i, ps) == False:
                    valid = False

            if category != 'Select your Category':
                if not is_offer_in_array(i, cats):
                    valid = False

            if company != 'Select your Company':
                if not is_offer_in_array(i, comps):
                    valid = False 
            
            if region != 'Select your Region':
                if not is_offer_in_array(i, regs):
                    valid = False

            if valid:
                all_offers.append(i)
        
        return render_template('index.html', offers=all_offers , regions=regions, companies=companies, position=position, category=category, region=region, company=company)


    return render_template('index.html', offers=ofs[:8] , regions=regions, companies=companies, position=None, category=None, region=None, company=None)

@views.route('/contact', methods=['GET', 'POST'])
def contact():

    if request.method == 'POST':
        full_name = request.form.get('full_name')
        email = request.form.get('email')
        message = request.form.get('message')

        sendMail("yassinebehilil@gmail.com","Mail from Jobless visitor", "Here is the message from "+full_name+" that has the email : "+email+" and sent this message : \n"+message)
        flash('Your message have been succesfully sent. You will soon get a response', category='success')
        return redirect('/contact')

    return render_template('contact.html')

@views.route('/home')
def homes():
    if isinstance(current_user, Candidate):
        return redirect('/home-candidate')
    elif isinstance(current_user, Recruiter):
        return redirect('/home-recruiter')
    else:
        return redirect('/')
    

@views.route('/home-candidate')
@login_required
def home_candidate():
    if isinstance(current_user, Recruiter):
        return redirect('/home-recruiter')

    apps = current_user.applications

    as_data = []

    for a in apps:
        
        if a.status == 'Pending':
            asa = {
                "offer": a.offer,
                "candidate": a.candidate,
                "appliers": len(a.offer.applications),
                "recruiter": a.offer.recruiter,
                "status": a.status,
                "dateApply": a.dateApply
            }
            as_data.append(asa)

    return render_template('home_candidate.html', user=current_user, apps=as_data)


@views.route('/home-recruiter')
@login_required
def home_recruiter():
    if isinstance(current_user, Candidate):
        return redirect('/home-candidate')

    ofs = Offer.query.filter_by(recruiter_id=current_user.id, status='active').all()

    
    of_data = []
    x = 1
    for offer in ofs:
        
        of = { 
            "id" : offer.id,
            "recruiter_id": offer.recruiter_id,
            "title": offer.title,
            "description": offer.description,
            "position": offer.position,
            "salary": offer.salary,
            "status": offer.status,
            "dateCreation": offer.dateCreation,
            "dateEnd": offer.dateEnd,
            "speciality": offer.speciality,
            "region": offer.region,
            "category":offer.category,
            "applications": [],
            "length": 0,
            "x": x,
        }

        for application in offer.applications:
            if application.candidate.status == 'active' and application.status != 'Canceled':
                ap ={
                    "id" : application.candidate.id,
                    "first_name": application.candidate.first_name,
                    "last_name": application.candidate.last_name,
                    "address": application.candidate.address,
                    "phone": application.candidate.phone,
                    "email": application.candidate.email,
                    "password": application.candidate.password,
                    "diploma": application.candidate.diploma,
                    "speciality": application.candidate.speciality,
                    "resume": application.candidate.resume,
                    "picture": application.candidate.picture,
                    "status": application.status,
                    "dateApply": application.dateApply
                }
                of["applications"].append(ap)
                x = x + 1

        of["length"] = len(of["applications"])  
        of["x"] = str(x)
        print("\n\n\n"+of["x"]+"\n\n\n")      
        of_data.append(of)
        x = x + 2
        
        

    
    return render_template('home_recruiter.html', user=current_user, offers=of_data)

@views.route('/profile-candidate', methods=['GET', 'POST'])
@login_required
def profile_candidate():
    if isinstance(current_user, Recruiter):
        return redirect('/home-recruiter')
    
    if request.method == 'POST':
        id = request.form.get('id')
        candidate = Candidate.query.filter_by(id=id).first()

        first_name = request.form.get('first_name').lower()
        last_name = request.form.get('last_name').lower()
        address = request.form.get('address').lower()
        phone = request.form.get('phone')
        email = request.form.get('email')
        password = request.form.get('password')
        diploma = request.form.get('diploma').lower()
        speciality = request.form.get('speciality').lower()

        resume = request.files['resume']
        picture = request.files['picture']

        candidate.first_name = first_name
        candidate.last_name = last_name 
        candidate.address = address 
        candidate.phone = phone 
        candidate.email = email 
        candidate.password = password

        candidate.diploma = diploma 
        candidate.speciality = speciality

        if resume:
            resumename = str(uuid.uuid4()) + os.path.splitext(resume.filename)[1]
            resume.save(os.path.join(upload_resume, resumename))
            candidate.resume = resumename

        if picture:
            picturename = str(uuid.uuid4()) + os.path.splitext(picture.filename)[1]

            image = Image.open(picture)
            resized_image = image.resize( (200, 200) )

            resized_image.save(os.path.join(upload_image, picturename))
            #picture.save(os.path.join(upload_image, picturename))
            candidate.picture = picturename

        db.session.commit()

        return redirect('/profile-candidate')


    return render_template("profile_candidate.html", user=current_user)


@views.route('/deactivate-candidate', methods=['GET', 'POST'])
@login_required
def deactivate_candidate():
    if isinstance(current_user, Recruiter):
        return redirect('/home-recruiter')

website/templates/browse_offers.html
{% extends "home_candidate.html" %}

{% block title %} Applications History {% endblock %}

{% block active %}
      <div class="collapse navbar-collapse" id="navbar-ex-3">
        <div class="navbar-nav me-auto">
          <a class="nav-item nav-link" href="/home">Home</a>
          <a class="nav-item nav-link " href="/applications-history">My Applications History</a>
          <a class="nav-item nav-link active" href="/browse-offers">Browse Offers</a>
        </div>
{% endblock  %}

{% block content %}

<div style="border : 1px solid #0A2463; width:100%; min-height:30rem; background-color:#E2E2E2; padding : 30px; padding-bottom:0;">
    

        
    <h3 style="color:#0A2463; top:5%;">Browse Offers </h3><br>
    <center>

            <h3 style="color:#0A2463;">Find Job, Employment, and Career Opportunities That Fits You </h3><br>
            <div class="divider divider-primary">
                <div class="divider-text" style="font-size:18px; color:#0A2463">Search for a job </div>
            </div>

            <br>
            <form method="post">

            <div style="margin:10px; padding: 30px;">

                {% if company is none and region is none and category is none and position is none %}
                <div class="input-group">
                    <input type="text" name="position"  placeholder="Search for your position " style="width:20%; border: 0px solid white;">

                    <select class="form-select" id="inputGroupSelect04" aria-label="example select " name="category"> 
                        <option>Select your Category</option>
                        <option value="Full Time">Full Time</option>
                        <option value="Part Time">Part Time</option>
                        <option value="Internship">Internship</option>
                        <option value="Freelance">Freelance</option>
                    </select>

                    <select class="form-select" id="inputGroupSelect04" aria-label="example select" name="company"> 
                        <option>Select your Company</option>
                        {% for c in companies %}
                            <option>{{ c[0]}}</option>
                        {% endfor %}
                        
                    </select>

                    <select class="form-select" id="inputGroupSelect04" aria-label="example select " name="region"> 
                        <option>Select your Region</option>
                        {% for r in regions %}
                            <option>{{ r[0] }}</option>
                        {% endfor %}
                    </select>

                    <button class="btn btn-outline-primary" type="submit" style="color:#0A2463; font-size:18px;">Search</button>
                </div>

                {% else %}

                <div class="input-group">
                    <input type="text"  placeholder="Search for your position " name="position" value="{{ position }}" style="width:20%; border: 0px solid white;">

                    <select class="form-select" id="inputGroupSelect04" aria-label="example select " name="category"> 
                        <option>Select your Category</option>
                        <option value="Full Time" {% if category == 'Full Time' %} selected {% endif %} >Full Time</option>
                        <option value="Part Time" {% if category == 'Part Time' %} selected {% endif %}>Part Time</option>
                        <option value="Internship" {% if category == 'Internship' %} selected {% endif %}>Internship</option>
                        <option value="Freelance" {% if category == 'Freelance' %} selected {% endif %}>Freelance</option>
                    </select>

                    <select class="form-select" id="inputGroupSelect04" aria-label="example select" name="company"> 
                        <option>Select your Company</option>
                        {% for c in companies %}
                            {% if c[0] == company %}
                                <option value="{{ c[0] }}" selected>{{ c[0] }}</option>
                            {% else %}
                                <option value="{{ c[0] }}">{{ c[0]}}</option>
                            {% endif %}
                        {% endfor %}
                        
                    </select>

                    <select class="form-select" id="inputGroupSelect04" aria-label="example select " name="region"> 
                        <option>Select your Region </option>
                        {% for r in regions %}
                            {% if r[0] == region %}
                                <option value="{{ r[0] }}" selected>{{ r[0] }}</option>
                            {% else %}
                                <option value="{{ r[0] }}">{{ r[0] }}</option>
                            {% endif %}

                        {% endfor %}
                    </select>

                    <button class="btn btn-outline-primary" type="submit" style="color:#0A2463; font-size:18px;">Search</button>
                </div>

                {% endif  %}

            </div>


            </form>

                    
    </center>


</div>

<div style="border : 1px solid #473198; width:100%;   background-color:#E3F3CD; padding : 30px;">


    <center>
        {% if company is none and region is none and category is none and position is none %}
        <h5 style="color:#473198">RECENTLY ADDED JOBS</h5>
        <h2 style="color:#473198">Featured Jobs Posts For This Week</h2>
        {% else %}
        <h2 style="color:#473198">HERE ARE YOUR RESULTS:</h2>
        {% endif %}
    
        <div style="margin:10px; padding: 30px; width:90%; min-height:650px;">

            <div class="row mb-5">

                {% for offer in offers  %}
                
                <div class="col-md-6 col-lg-3 mb-2">
                      <div class="card h-100">
                        <img class="card-img-top" src="{{ url_for('views.serve_picture', filename=offer.recruiter.picture ) }}" height="170px" alt="Card image cap" />
                        <div class="card-body">
                          <h5 class="card-title">{{ offer.title }}</h5>
                          <p class="card-text">
                            {{ offer.description }}
                          </p>
                          <p class="card-text">
                            {{ offer.region }}
                          </p>
                          <a href="/candidate-offer-profile/{{ offer.id }}" class="btn btn-outline-success">Read More</a>
                          <a href="/apply-offer/{{ offer.id }}" class="btn btn-outline-info">Apply</a>

                        </div>
                      </div>

                </div>

                {% endfor %}

            </div>   
            
            
        </div>

    </center>

</div>


{% endblock %}

website/templates/candidate_profile.html
{% extends "home_recruiter.html" %}

{% block head %}
<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
  data-theme="theme-default"
  dataassets-path="{{ url_for('static' , filename='assets/') }}"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>Candidate </title>

    <meta name="description" content="" />

   
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='assets/vendor/fonts/boxicons.css') }}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='assets/vendor/css/core.css') }}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='assets/vendor/css/theme-default.css') }}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='assets/css/demo.css') }}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css') }}" />

    <link rel="stylesheet" href="{{ url_for('static' , filename='assets/vendor/libs/apex-charts/apex-charts.css') }}" />

    <!-- Page CSS -->

    <!-- Helpers -->
    <script src="{{ url_for('static' , filename='assets/vendor/js/helpers.js') }}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{{ url_for('static' , filename='assets/js/config.js') }}"></script>

    <style>
        
    </style>

  </head>
  
{% endblock %}

{% block active %}
      <div class="collapse navbar-collapse" id="navbar-ex-3">
        <div class="navbar-nav me-auto">
          <a class="nav-item nav-link" href="/home">Home</a>
            <a class="nav-item nav-link " href="/add-offer">Add Offer </a>
            <a class="nav-item nav-link" href="/offers-history">My Offers History</a>
            <a class="nav-item nav-link" href="/accept-refuse-offers">A/R Application</a>
        </div>
{% endblock %}



{% block content  %}

<div style="border : 1px solid #473198; width:100%;   background-color:#E3F3CD; padding : 30px;">
    

  <center>
  <!-- <h3 style="color:#473198; top:5%;">Profile Details </h3><br> -->
  
  <div style="width:90%;">

      <div class="card mb-4">
          <h5 class="card-header"></h5>
          <!-- Account -->
          
          
          <div class="card-body">
              
              <center>

                  <img src="{{ url_for('views.serve_picture', filename=candidate.picture ) }}" height="200px" width="200px" /><br><br>
                  
                  <!-- <h3 style="color:#473198;">Searching for a full stack developer</h3><br> -->
                  <p><h4 style="color:#473198;">Full Name : </h4>{{ candidate.last_name + " "+ candidate.first_name }}</p>
                  <p ><h4 style="color:#473198;">Email :  </h4> {{ candidate.email }} </p>
                  <p><h4 style="color:#473198;">Address : </h4> {{ candidate.address }}</p>
                  <p><h4 style="color:#473198;"> Phone : </h4> {{ candidate.phone }}</p>
                  <p><h4 style="color:#473198;">Speciality : </h4> {{ candidate.speciality }}</p>
                  <p><h4 style="color:#473198;">Diploma : </h4> {{ candidate.diploma }}</p>
                  <br>
                  

                  

                  
                  <br><br>
              </center>
              
            
          </div>

          <!-- /Account -->
        </div>
        

        


        </div>

    
  </center>


</div>




<div class="buy-now">
  <a
    href="#"
    target="_blank"
    class="btn btn-danger btn-resume-now"
    data-bs-toggle="modal" data-bs-target="#contact-candidate"
    >Contact Candidate</a
  >

  <form method="post">
  <div class="modal fade" id="contact-candidate" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="exampleModalLabel1">Contact Candidate</h4>
          
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>

        </div>

        <div class="modal-body">

            <div class="card-body" >

                  <div class="mb-3 col-md-12">

                      <label class="form-label">From</label>
                      <div class="input-group input-group-merge">

                          <input
                          type="text"
                          class="form-control"
                          id="sender"
                          name="sender"
                          value="{{ user.email }}"
                          readonly
                        />
                      </div>
                  </div>

                  <div class="mb-3 col-md-12">

                      <label class="form-label">To</label>
                      <div class="input-group input-group-merge">

                          <input
                          type="text"
                          class="form-control"
                          id="receiver"
                          name="receiver"
                          value="{{ candidate.email }}"
                          readonly
                        />
                      </div>
                    </div>

                  <div class="mb-3 col-md-12">

                    <label class="form-label">Message</label>
                    <div class="input-group input-group-merge">

                      <textarea class="form-control" name="message" rows="5" ></textarea>
                    </div>
                  </div>

                  
                  

                </div>
            



            </div>



        



        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
            Close
          </button>
          <button type="submit" class="btn btn-primary">Send</button>
        </div>

      </div>

    </div>
    </div>

  </form>


  <a
    href="https://themeselection.com/products/sneat-bootstrap-html-admin-template/"
    target="_blank"
    class="btn btn-danger btn-contact-now"
    data-bs-toggle="modal" data-bs-target="#show-resume"
    >Show Resume</a
  >

         
  <div class="modal fade" id="show-resume" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel1">Candidate Resume</h5>
            
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>

          </div>

          <div class="modal-body">
              

              <iframe src="{{ url_for('views.serve_resume', filename=candidate.resume ) }}" height="550" width="100%" title="Resume" ></iframe>



          </div>



          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
              Close
            </button>
            
          </div>

        </div>
      </div>
    </div>

  
  
</div>

{% endblock %}

website/templates/visitor_offer_profile.html
{% extends "index.html" %}

{% block title %} Offer Profile {% endblock %}

{% block active %}
      <div class="collapse navbar-collapse" id="navbar-ex-3">
        <div class="navbar-nav me-auto">
          <a class="nav-item nav-link" href="/">Home</a>
          <a class="nav-item nav-link" href="/contact">Contact</a>
        </div>
        {% endblock %}

{% block content %}

<div style="border : 1px solid #473198; width:100%;   background-color:#E3F3CD; padding : 30px;">
    

    <center>
    <!-- <h3 style="color:#473198; top:5%;">Profile Details </h3><br> -->
    
    <div style="width:90%;">

        <div class="card mb-4">
            <h5 class="card-header"></h5>
            <!-- Account -->
            
            
            <div class="card-body">
                
                <center>
                    
                    <h3 style="color:#473198;">{{ offer.title }}</h3><br>
                    <p><h5 style="color:#473198;">Description : </h5>{{ offer.description }} </p>
                    <p ><h5 style="color:#473198;">Position :  </h5> {{ offer.position }} </p>
                    <p><h5 style="color:#473198;">Salary : </h5> {{ offer.salary }}</p>
                    <p><h5 style="color:#473198;">Date Creation : </h5> {{ offer.dateCreation }}</p>
                    <p><h5 style="color:#473198;">Date Of Expiration : </h5> {{ offer.dateEnd }}</p>
                    <p><h5 style="color:#473198;">Speciality : </h5>{{ offer.speciality }}</p>
                    <p><h5 style="color:#473198;">Region : </h5> {{ offer.region }}</p>
                    <p><h5 style="color:#473198;">Recruiter : </h5> {{ offer.recruiter.first_name + "  " + offer.recruiter.last_name }}</p>
                    <p><h5 style="color:#473198;">Category : </h5> {{ offer.category }}</p>
                    <p><h5 style="color:#473198;">Company Name : </h5> {{ offer.recruiter.company }}</p>
                    <p><h5 style="color:#473198;">Company Logo : </h5> <img src="{{ url_for('views.serve_picture', filename=offer.recruiter.picture ) }}" height="80px" width="80px" alt="company_logo" /></p>
                    <br><br>
                    <br>

                    

                    

                        
                    </div>
                    
                    </div>
                    <br><br>
                </center>
                
              
            </div>

            <!-- /Account -->
          </div>
          

          


          </div>

      
    </center>


</div>


<div class="buy-now">

    
    
    <a href="/register" class="btn btn-danger btn-contact-now" >Apply</a>

    <a href="/register"class="btn btn-danger btn-resume-now"> Contact Recruiter </a>


    

</div>


{% endblock %}